<?php
require_once 'config/db.php';
require_once 'includes/auth.php';
ensureLogin();

$job = $_GET['job'] ?? '';
if (!$job) die('Missing job id.');

$userId = $_SESSION['user_id'];
$userRole = $_SESSION['user_role'] ?? '';

$stmt = $pdo->prepare('SELECT * FROM invoices WHERE job_card_id = ? LIMIT 1');
$stmt->execute([$job]);
$inv = $stmt->fetch();
if (!$inv) die('Invoice not found.');

$job_stmt = $pdo->prepare('SELECT j.*, v.brand, v.model, v.customer_id, u.name AS customer_name FROM job_cards j JOIN vehicles v ON j.vehicle_no = v.vehicle_no JOIN users u ON v.customer_id = u.id WHERE j.job_card_id = ? LIMIT 1');
$job_stmt->execute([$job]);
$jobrow = $job_stmt->fetch();
if (!$jobrow) die('Job not found.');

// Authorization
if (!($userRole === 'ADMIN' || $userRole === 'MECHANIC' || ($userRole === 'CUSTOMER' && intval($jobrow['customer_id']) === intval($userId)))) {
    die('Unauthorized to view this invoice.');
}

// Build invoice HTML (simple, styled inline for PDF)
$company_name = '911 Garage';
$invoice_html = '<!doctype html><html><head><meta charset="utf-8"><title>Invoice ' . htmlspecialchars($inv['invoice_no']) . '</title>';
$invoice_html .= '<style>body{font-family: DejaVu Sans, Arial, sans-serif; margin:24px; color:#222} .h{font-size:20px;font-weight:700} .muted{color:#666} table{width:100%;border-collapse:collapse;margin-top:12px} th,td{padding:8px;border:1px solid #ddd;text-align:left} .right{text-align:right} .tot{font-weight:700}</style>';
$invoice_html .= '</head><body>';
$invoice_html .= '<div><div class="h">' . $company_name . '</div><div class="muted">Invoice: ' . htmlspecialchars($inv['invoice_no']) . '</div></div>';
$invoice_html .= '<hr>';
$invoice_html .= '<div><strong>Customer:</strong> ' . htmlspecialchars($jobrow['customer_name']) . '<br><strong>Vehicle:</strong> ' . htmlspecialchars($jobrow['brand'] . ' ' . $jobrow['model'] . ' (' . $jobrow['vehicle_no'] . ')') . '</div>';
$invoice_html .= '<table><thead><tr><th>Description</th><th class="right">Amount (₹)</th></tr></thead><tbody>';
$invoice_html .= '<tr><td>Service Charges</td><td class="right">' . number_format($inv['service_charges'],2) . '</td></tr>';
$invoice_html .= '<tr><td colspan="2"><strong>Parts Used</strong></td></tr>';
// fetch parts used
$parts_stmt = $pdo->prepare('SELECT j.part_code, j.quantity_used, i.part_name, i.price_per_unit FROM job_parts_used j LEFT JOIN inventory i ON j.part_code = i.part_code WHERE j.job_card_id = ?');
$parts_stmt->execute([$job]);
$parts = $parts_stmt->fetchAll();
if ($parts) {
    foreach ($parts as $p) {
        $line = ($p['price_per_unit'] ?? 0) * ($p['quantity_used'] ?? 0);
        $invoice_html .= '<tr><td>' . htmlspecialchars(($p['part_name'] ?: $p['part_code']) . ' &times; ' . intval($p['quantity_used'])) . '</td><td class="right">' . number_format($line,2) . '</td></tr>';
    }
} else {
    $invoice_html .= '<tr><td colspan="2" class="muted">No parts recorded</td></tr>';
}
$invoice_html .= '<tr><td>Parts Charges</td><td class="right">' . number_format($inv['parts_charges'],2) . '</td></tr>';
$invoice_html .= '<tr><td>CGST</td><td class="right">' . number_format($inv['cgst'],2) . '</td></tr>';
$invoice_html .= '<tr><td>SGST</td><td class="right">' . number_format($inv['sgst'],2) . '</td></tr>';
$invoice_html .= '<tr><td class="tot">Total Payable</td><td class="right tot">' . number_format($inv['total_payable'],2) . '</td></tr>';
$invoice_html .= '</tbody></table>';
$invoice_html .= '<div style="margin-top:18px; font-size:12px; color:#666">Payment Status: ' . htmlspecialchars($inv['payment_status']) . '</div>';
$invoice_html .= '<div style="margin-top:28px; color:#999; font-size:11px">Generated by 911 Garage</div>';
$invoice_html .= '</body></html>';

// If Dompdf available, render PDF
// Try to load Composer autoloader if present so Dompdf classes are available
$autoload = __DIR__ . '/vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
}

if (class_exists('Dompdf\\Dompdf')) {
    // Use Dompdf to generate PDF
    $dompdf = new \Dompdf\Dompdf();
    $dompdf->loadHtml($invoice_html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();
    $filename = 'invoice_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $inv['invoice_no']) . '.pdf';
    // Stream the PDF to the browser
    $dompdf->stream($filename, array('Attachment' => 1));
    exit;
} else {
    // Fallback: show HTML and instructions to install Dompdf
    echo '<div style="max-width:900px;margin:24px auto;font-family:Arial,Helvetica,sans-serif">';
    echo '<h2>PDF generator not installed</h2>';
    echo '<p>To enable PDF download, install <strong>Dompdf</strong> via Composer on this project:</p>';
    echo '<pre>composer require dompdf/dompdf</pre>';
    echo '<p>After installing, refresh this page to download the PDF.</p>';
    echo '<hr>';
    echo $invoice_html; // render HTML preview
    echo '</div>';
    exit;
}
